disabled_rules: # rule identifiers to exclude from running
  #- line_length 
  - todo
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

line_length:
  ignores_comments: true
  ignores_function_declarations: true
  ignores_urls: true
  warning: 200
  error: 300

large_tuple:
  warning: 5
  error: 7

function_body_length:
  warning: 60
  error: 120

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 80
    error: 100

type_name:
  min_length:
    warning: 2
  max_length:
    warning: 60
    error: 70

type_body_length:
  warning: 250
  error: 400

function_parameter_count:
  warning: 8
  error: 12

trailing_whitespace:
  ignores_empty_lines: true

cyclomatic_complexity:
   warning: 15
   error: 25